# Syringe Dependencies
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

required = [
  "k8s.io/code-generator/cmd/client-gen",

  # Needed by github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/
  "github.com/ghodss/yaml",

  # Needed by github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/
  "github.com/golang/protobuf/descriptor",

  # Fixing dumb issue with codegangsta/cli
  "github.com/cpuguy83/go-md2man",
  "github.com/russross/blackfriday"
]

[[constraint]]
  branch = "master"
  name = "github.com/russross/blackfriday"

[[constraint]]
  branch = "master"
  name = "github.com/fatih/color"

# [[constraint]]
#   name = "github.com/golang/protobuf"
#   version = "1.2.0"

# Doing this for now, so protobuf package can be updated to latest and make protoc happy
[[override]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/handlers"

[[override]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.11.1"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "~1.6.3"

[[constraint]]
  branch = "master"
  name = "github.com/philips/go-bindata-assetfs"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.27.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.3"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.3"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  branch = "master"

# github.com/nre-learning/syringe/vendor/google.golang.org/grpc/internal/channelz
# vendor/google.golang.org/grpc/internal/channelz/types_linux.go:41:15: undefined: unix.GetsockoptLinger
# vendor/google.golang.org/grpc/internal/channelz/types_linux.go:44:15: undefined: unix.GetsockoptTimeval
# vendor/google.golang.org/grpc/internal/channelz/types_linux.go:47:15: undefined: unix.GetsockoptTimeval
[[override]]
  name = "golang.org/x/sys"
  branch = "master"
  
[[override]]
  name = "github.com/ghodss/yaml"
  version = "v1.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false

[[prune.project]]
  name = "k8s.io/gengo"
  unused-packages = false

[[prune.project]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  # Please do not remove this, we are relying on this to build binaries
  unused-packages = false

[[prune.project]]
  name = "github.com/russross/blackfriday"
  unused-packages = false


