---
curriculumDir: /home/mierdin/Code/GO/src/github.com/nre-learning/antidote-test-curriculum
instanceId: antidote-dev
enabledServices:
- api
- stats
- scheduler

# for dev
k8sInCluster: false
k8sOutOfClusterConfigPath: "/home/mierdin/.kube/selfmedicateconfig"
